# Creating arrays with Numby

In [38]:
import numpy as np

In [3]:
np.zeros(3)
# np.ones()
# np.array([])
# np.full(dim, number) == np.ones(dim)*num

array([0., 0., 0.])

## Indexing and Slicing

In [39]:
my_list = [1,2,3,4,5]
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4, 5])

In [42]:
my_list = [1,2,3,4,5]
my_array = np.array(my_list)
# converting list to array
last_element = my_array[-1]
print(my_array[-2])
print(last_element)
sub_array = my_array[0:4]
sub_array

4
5


array([1, 2, 3, 4])

In [15]:
my_array1 = np.array([1,2,3,4,5])
first_element = my_array1[0]
last_element = my_array1[-1]
sum_first_last = first_element + last_element
print(f"The sum of first and last element in my array = {sum_first_last}")
my_array1
my_array[0] = 10
new_first_element = my_array[0]
sm = new_first_element + last_element
print(f"The sum of first and last element in my array = {sm}")

The sum of first and last element in my array = 6
The sum of first and last element in my array = 15


## Arrays built-in functions

In [21]:
np.arange(5)
# result : array([0,1,2,3,4])
# How does this result? => loop with 5 iterations starting from 0 with step 1

array([0, 1, 2, 3, 4])

In [22]:
np.arange(2,10,3)
# result : array([2,5,8])
# process : loop with limit condition iterations (next < 10) start from 2 with step 3

array([2, 5, 8])

In [23]:
np.linspace(0,10,11)
# result : array([0. ,1. ,2. ,3. ,4. ,5. ,6. ,7. ,8. ,9. ,10.]) -- including the stop value 10
# process : loop with condition (next <= 10) start from 0 -- next = start + (start+stop/n_elements-1)


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

## Two-Dimensional Arrays

In [24]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Accessing and Assignment for 2-Dim

In [32]:
matrix1 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

row_access = matrix1[1]
print(row_access)
# result : array([5,6,7,8])

col_access = matrix1[:,1]
print(col_access)
# result : array([2,6,10])

ele_access = matrix1[2,3]
print(ele_access)

mul_col_access = matrix1[:,[0,1]]
print(mul_col_access)
# print all first and second columns

n1 = matrix1[[0,1], 0:3]
print(n1)
# print first 2 rows with only 3 columns

[5 6 7 8]
[ 2  6 10]
12
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[1 2 3]
 [5 6 7]]


In [37]:
matrix1 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
matrix1[0] = [5,6,7,8]
matrix1[2,3] = 1
matrix1

array([[ 5,  6,  7,  8],
       [ 5,  6,  7,  8],
       [ 9, 10, 11,  1]])

## Generate random arrays