# Creating arrays with Numby

In [2]:
import numpy as np

In [3]:
np.zeros(3)
# np.ones()
# np.array([])
# np.full(dim, number) == np.ones(dim)*num

array([0., 0., 0.])

## Indexing and Slicing

In [39]:
my_list = [1,2,3,4,5]
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4, 5])

In [42]:
my_list = [1,2,3,4,5]
my_array = np.array(my_list)
# converting list to array
last_element = my_array[-1]
print(my_array[-2])
print(last_element)
sub_array = my_array[0:4]
sub_array

4
5


array([1, 2, 3, 4])

In [15]:
my_array1 = np.array([1,2,3,4,5])
first_element = my_array1[0]
last_element = my_array1[-1]
sum_first_last = first_element + last_element
print(f"The sum of first and last element in my array = {sum_first_last}")
my_array1
my_array[0] = 10
new_first_element = my_array[0]
sm = new_first_element + last_element
print(f"The sum of first and last element in my array = {sm}")

The sum of first and last element in my array = 6
The sum of first and last element in my array = 15


## Arrays built-in functions

In [21]:
np.arange(5)
# result : array([0,1,2,3,4])
# How does this result? => loop with 5 iterations starting from 0 with step 1

array([0, 1, 2, 3, 4])

In [22]:
np.arange(2,10,3)
# result : array([2,5,8])
# process : loop with limit condition iterations (next < 10) start from 2 with step 3

array([2, 5, 8])

In [23]:
np.linspace(0,10,11)
# result : array([0. ,1. ,2. ,3. ,4. ,5. ,6. ,7. ,8. ,9. ,10.]) -- including the stop value 10
# process : loop with condition (next <= 10) start from 0 -- next = start + (start+stop/n_elements-1)


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

## Two-Dimensional Arrays

In [24]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Accessing and Assignment for 2-Dim

In [32]:
matrix1 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

row_access = matrix1[1]
print(row_access)
# result : array([5,6,7,8])

col_access = matrix1[:,1]
print(col_access)
# result : array([2,6,10])

ele_access = matrix1[2,3]
print(ele_access)

mul_col_access = matrix1[:,[0,1]]
print(mul_col_access)
# print all first and second columns

n1 = matrix1[[0,1], 0:3]
print(n1)
# print first 2 rows with only 3 columns

[5 6 7 8]
[ 2  6 10]
12
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[1 2 3]
 [5 6 7]]


In [37]:
matrix1 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
matrix1[0] = [5,6,7,8]
matrix1[2,3] = 1
matrix1

array([[ 5,  6,  7,  8],
       [ 5,  6,  7,  8],
       [ 9, 10, 11,  1]])

## Generate random arrays

In [ ]:
# np.random.rand(size)
np.random.rand(5,2)
# here we didn't identify sees so he will generate new seed every time we run from timestamp

array([[0.87736859, 0.24678836],
       [0.11891739, 0.92811214],
       [0.39629746, 0.05674409],
       [0.1445427 , 0.93978246],
       [0.58538951, 0.30949097]])

In [14]:
np.random.seed(2)
# here we determine seed number (inital number)
default_rand_range = np.random.rand(5, 2)
# the result will be same with every run
# rand function return values from 0:1 only
modified_random_range = np.random.rand(4)*4
# here will return pesudo random numbers from 0:4
print(default_rand_range)
print(modified_random_range)

[[0.4359949  0.02592623]
 [0.54966248 0.43532239]
 [0.4203678  0.33033482]
 [0.20464863 0.61927097]
 [0.29965467 0.26682728]]
[2.48453533 2.11656838 0.53831978 2.05431249]


In [15]:
import time
now = time.time() 
# reteurn time with sec from Epoch time : 1/1/1970 - 00:00:00
readable = time.ctime(now)
print(now)
print(readable)

1758848721.843261
Fri Sep 26 01:05:21 2025


In [ ]:
np.random.seed(2)
print(np.random.randn(10))            # 10 ارقام عشوائية من ال Normall distribution
# np.random.randint(low=?, high=?, size=None)
print(np.random.randint(10))          # رقم واحد من 0 لحد 9
print(np.random.randint(1, 10))       # رقم واحد من 1 لحد 9
print(np.random.randint(1, 10, 5))    # Array 1D فيه 5 عناصر
print(np.random.randint(1, 10, (2, 3))) # Array 2x3

[-0.41675785 -0.05626683 -2.1361961   1.64027081 -1.79343559 -0.84174737
  0.50288142 -1.24528809 -1.05795222 -0.90900761]
4
6
[8 4 7 5 4]
[[8 7 2]
 [4 6 9]]


## Element-Wise operations

### Arthematic Operations

In [24]:
my_array = np.arange(10).reshape(2,5)
print(my_array)
equ1 = (my_array * 2) + 1
print(equ1)
equ2 = my_array **2
print(equ2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 1  3  5  7  9]
 [11 13 15 17 19]]
[[ 0  1  4  9 16]
 [25 36 49 64 81]]


In [10]:
arr1 = np.array([[1,2,3,4], [5,6,7,8]])
arr2 = np.array([[9,10,11,12], [13,14,15,16]])
sum_arrs = arr1 + arr2
print(sum_arrs)
mul_arrs = arr1*arr2
print(mul_arrs)

[[10 12 14 16]
 [18 20 22 24]]
[[  9  20  33  48]
 [ 65  84 105 128]]


### Comparison Operations

In [ ]:
arr1 = np.array([[1,2,3,4], [5,6,7,8]])
arr2 = np.array([[9,10,11,12], [13,14,15,16]])
print(arr1 >= 2)
print(arr1>arr2)
arr1[arr1>2]
# this line returns all elements in this array that achieve this condition (sub_array)

[[False  True  True  True]
 [ True  True  True  True]]
[[False False False False]
 [False False False False]]


array([3, 4, 5, 6, 7, 8])

### Summarizing Operations

In [ ]:
arr1 = np.array([[1,2,3,4], [5,6,7,8]])
print(arr1.max())
print(arr1.min())
print(arr1.sum())
print(arr1.mean())
print(arr1.std())
# all works with 1-Dim and 2-dim

8
1
36
4.5
2.29128784747792


## Linear Algebra Operations

### vector-vector Multiplication

In [24]:
# dot product

def vv_mul(u,v):
    assert u.shape[0] == v.shape[0]
    # u.shape => tuple = (x,y) -- x means number of rows and y means number of coulmns
    arr1 = u*v
    result = 0
    for i in arr1:
        result = result + i

    return result

import numpy as np
u = np.array([2,4,5,6])
v = np.array([1,0,0,2])
# direct method
result1 = u.dot(v)
print(result1)

# own-function method
result2 = vv_mul(u,v)
print(result2)

14
14


In [10]:
u = np.array([[2,4,5,6],[1,2,3,4]])
v = np.array([1,2,3,4])
v.shape[0]

4

In [ ]:
u = np.array([2,4,5,6])
v = np.array([1,2,3,4])
assert u.shape[0] == v.shape[0]
# assert function here checked the condition: if true (will continue) if not will excute an assertation error
print(u+v)

[ 3  6  8 10]


### Matrix-vector Multiplication

In [2]:
def mv_mul(u,v):
    assert u.shape[1] == v.shape[0]
    result_arr = np.empty(u.shape[0])
    for i in range(u.shape[0]):
        result_arr[i] = u[i].dot(v)

    return result_arr

import numpy as np
u = np.array([[2, 4, 5, 6], [1, 2, 1, 2], [3, 1, 2, 1]])
v = np.array([1,0.5,2,1])
result = mv_mul(u,v)
result


array([20. ,  6. ,  8.5])