In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
max1 = np.full((3,3), 3)
max1

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [8]:
np.ones(4)

array([1., 1., 1., 1.])

In [9]:
np.ones(4 , dtype=int)

array([1, 1, 1, 1])

In [10]:
my_array = np.array([1,2,5,7,18])
my_array

array([ 1,  2,  5,  7, 18])

In [11]:
my_array[0]

np.int64(1)

In [12]:
my_array[3]

np.int64(7)

In [13]:
my_array[3] = 10

In [14]:
my_array

array([ 1,  2,  5, 10, 18])

In [22]:
np.arange(5, dtype=float)

array([0., 1., 2., 3., 4.])

In [18]:
np.arange(2,5,2)
# arange([start - optional], stop, [step] , dtype=int)
# default start = 0 , default step = 1

array([2, 4])

In [19]:
np.linspace(0,10,10)
# linspace(start_value, stop_value, elements_num, endpoint=True)
# endpoint here by default is True so he will include the stop value 10. So the equation: (start+stop/elements_num-1)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [21]:
np.linspace(0,10,10, endpoint=False)
# endpoint = False, So the equation: (start+stop/elements_num)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

# Create a two-dimensional array and access elements


In [25]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


In [28]:
max1 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]])
max1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
max1[1,2]
# print the number in second rowwith index 1 and the third col with index 2 => 7

np.int64(7)

In [30]:
max1[1]
# print the second row with index 1

array([5, 6, 7, 8])

In [33]:
max1[0] = [1,1,1,1]
max1

array([[ 1,  1,  1,  1],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
max1[:,1]
# print the second col. (we put ':' to include all rows)

array([ 1,  6, 10])

In [39]:
max1[1:3,1]


array([ 6, 10])

In [40]:
max1[1, 0:3]

array([5, 6, 7])

In [41]:
max1[1, 0:6]

array([5, 6, 7, 8])

# Random Arrays